"""
main.py — Yoga Pose Feedback System
=====================================
Entry point. Loads config.json and pose_references.json,
opens the webcam, and runs the real-time feedback loop.

Requirements
────────────
  pip install mediapipe opencv-python numpy

Files needed in the same directory
───────────────────────────────────
  config.json           ← parameters
  pose_references.json  ← generated by build_references.py
  pose_landmarker.task  ← MediaPipe model

Controls
────────
  1 / 2 / 3  — select pose
  Q / Esc    — quit
"""

import csv
import glob
import json
import os
import sys
import time

import cv2
import mediapipe as mp
import numpy as np
from mediapipe.tasks import python as mp_python
from mediapipe.tasks.python import vision as mp_vision

from analyzer import ANGLE_INDICES, FeedbackResult, compute_feedback
from audio    import AudioFeedback
from session  import Session
from smoother import FeedbackSmoother


# ─────────────────────────────────────────────────────────────────
#  STARTUP — load config and references
# ─────────────────────────────────────────────────────────────────
def load_config(path="config.json") -> dict:
    if not os.path.exists(path):
        print(f"[ERROR] {path} not found.")
        sys.exit(1)
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_refs(path: str) -> dict:
    """Load pose_references.json. Returns {} if not found (triggers fallback in analyzer)."""
    if not os.path.exists(path):
        print(f"[WARN] {path} not found — no dataset references loaded.")
        print("       Run:  python build_references.py --yoga82 Yoga-82/")
        return {}
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    # Normalise: ensure every value has "target" and "tolerance" floats
    refs = {}
    for pose, angles in data.items():
        refs[pose] = {}
        for angle, v in angles.items():
            refs[pose][angle] = {
                "target":    float(v["target"]),
                "tolerance": float(v["tolerance"]),
            }
    return refs


# ─────────────────────────────────────────────────────────────────
#  MEDIAPIPE INIT
# ─────────────────────────────────────────────────────────────────
def init_landmarker(model_path: str):
    opts = mp_vision.PoseLandmarkerOptions(
        base_options=mp_python.BaseOptions(model_asset_path=model_path),
        running_mode=mp_vision.RunningMode.VIDEO,
        num_poses=1,
    )
    return mp_vision.PoseLandmarker.create_from_options(opts)


# ─────────────────────────────────────────────────────────────────
#  REFERENCE PHOTO SYSTEM
#  Loads one representative image per pose from the Yoga-82 cache.
#  Falls back gracefully (no crash, no photo shown) if images aren't found.
# ─────────────────────────────────────────────────────────────────

# Maps canonical pose names to Yoga-82 folder name patterns (lowercase)
_POSE_FOLDER_PATTERNS = {
    "Warrior I": ["warrior_i_pose", "virabhadrasana_i"],
    "Tree Pose": ["tree_pose", "vrksasana", "vriksasana"],
    "Triangle":  ["triangle_pose", "trikonasana", "utthita_trikonasana"],
}

_IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}


def _find_pose_folder(yoga82_dir: str, pose_name: str) -> str | None:
    """
    Return the path of the best-matching Yoga-82 subfolder for a pose.
    Uses regex word-boundary matching (same logic as normalise_name in
    build_references.py) so "virabhadrasana_i" does not match
    "virabhadrasana_iii_", and "warrior_i_pose" does not match
    "warrior_iii_pose_...".
    """
    import re
    patterns = _POSE_FOLDER_PATTERNS.get(pose_name, [])
    if not patterns or not os.path.isdir(yoga82_dir):
        return None

    # Sort patterns longest-first so more specific patterns win
    patterns_sorted = sorted(patterns, key=len, reverse=True)

    try:
        for folder in sorted(os.listdir(yoga82_dir)):
            key = re.sub(r"[^a-z0-9]+", "_", folder.lower()).strip("_")
            for p in patterns_sorted:
                pattern = r"(?:^|_)" + re.escape(p) + r"(?:_|$)"
                if re.search(pattern, key):
                    full = os.path.join(yoga82_dir, folder)
                    if os.path.isdir(full):
                        return full
    except OSError:
        pass
    return None


def load_reference_photos(config: dict) -> dict:
    """
    For each pose try to load a reference photo.
    Priority:
      1. config["poses"][pose]["reference_image"] (explicit path override)
      2. First valid cached image in the matching Yoga-82 sub-folder

    Returns { pose_name: bgr_ndarray | None }
    """
    yoga82_dir = config.get("yoga82_dir", "Yoga-82")
    photos     = {}

    for pose_name, pose_cfg in config["poses"].items():
        img = None

        # 1. Explicit override in config
        explicit = pose_cfg.get("reference_image")
        if explicit and os.path.isfile(explicit):
            img = cv2.imread(explicit)

        # 2. Auto-discover from Yoga-82 cache
        if img is None:
            folder = _find_pose_folder(yoga82_dir, pose_name)
            if folder:
                for fname in sorted(os.listdir(folder)):
                    if os.path.splitext(fname)[1].lower() in _IMG_EXTS:
                        candidate = cv2.imread(os.path.join(folder, fname))
                        if candidate is not None:
                            img = candidate
                            break

        photos[pose_name] = img
        status = "✓" if img is not None else "✗ (not found)"
        print(f"  Reference photo [{pose_name}]: {status}")

    return photos


def draw_pose_reference(frame, photo, bx: int, by: int,
                        bw: int = 130, bh: int = 165):
    """
    Display a reference photo in the right panel.
    Scales the image to fill the box while preserving aspect ratio.
    If photo is None, shows a placeholder message.
    """
    draw_rounded_rect(frame, bx, by, bx + bw, by + bh, 8, (28, 28, 28), 0.80)
    cv2.putText(frame, "Reference", (bx + 8, by + 14),
                cv2.FONT_HERSHEY_SIMPLEX, 0.34, (150, 150, 150), 1)

    if photo is None:
        cv2.putText(frame, "no image", (bx + 22, by + bh // 2),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.35, (90, 90, 90), 1)
        return

    # Available draw area inside the box
    area_x, area_y = bx + 2,  by + 20
    area_w, area_h = bw - 4,  bh - 22

    h_img, w_img = photo.shape[:2]
    scale   = min(area_w / w_img, area_h / h_img)
    new_w   = int(w_img * scale)
    new_h   = int(h_img * scale)
    resized = cv2.resize(photo, (new_w, new_h), interpolation=cv2.INTER_AREA)

    # Centre inside area
    ox = area_x + (area_w - new_w) // 2
    oy = area_y + (area_h - new_h) // 2

    # Guard against going out of frame bounds
    oy = max(0, min(oy, frame.shape[0] - new_h))
    ox = max(0, min(ox, frame.shape[1] - new_w))
    frame[oy:oy + new_h, ox:ox + new_w] = resized

SKELETON_CONNECTIONS = [
    (11, 13), (13, 15), (12, 14), (14, 16),
    (15, 17), (15, 19), (16, 18), (16, 20),
    (23, 25), (25, 27), (24, 26), (26, 28),
    (11, 12), (23, 24), (11, 23), (12, 24),
    ( 0, 11), ( 0, 12),
]


# ─────────────────────────────────────────────────────────────────
#  DRAWING HELPERS
# ─────────────────────────────────────────────────────────────────
def draw_rounded_rect(img, x1, y1, x2, y2, r, color, alpha=0.60):
    ov = img.copy()
    cv2.rectangle(ov, (x1 + r, y1), (x2 - r, y2), color, -1)
    cv2.rectangle(ov, (x1, y1 + r), (x2, y2 - r), color, -1)
    for cx, cy in [(x1+r, y1+r), (x2-r, y1+r), (x1+r, y2-r), (x2-r, y2-r)]:
        cv2.circle(ov, (cx, cy), r, color, -1)
    cv2.addWeighted(ov, alpha, img, 1 - alpha, 0, img)


def draw_skeleton(frame, lm_2d, joint_colors: dict):
    h, w = frame.shape[:2]
    for si, ei in SKELETON_CONNECTIONS:
        if si >= len(lm_2d) or ei >= len(lm_2d):
            continue
        ls, le = lm_2d[si], lm_2d[ei]
        if getattr(ls, "visibility", 1) < 0.4 or getattr(le, "visibility", 1) < 0.4:
            continue
        xs, ys = int(ls.x * w), int(ls.y * h)
        xe, ye = int(le.x * w), int(le.y * h)
        cs  = joint_colors.get(si, (200, 200, 200))
        ce  = joint_colors.get(ei, (200, 200, 200))
        seg = tuple(int(v) for v in ((np.array(cs) + np.array(ce)) // 2))
        cv2.line(frame, (xs, ys), (xe, ye), seg, 2)

    for idx, lm in enumerate(lm_2d):
        if getattr(lm, "visibility", 1) < 0.4:
            continue
        x, y = int(lm.x * w), int(lm.y * h)
        col  = joint_colors.get(idx, (180, 180, 180))
        cv2.circle(frame, (x, y), 5, col, -1)
        cv2.circle(frame, (x, y), 5, (255, 255, 255), 1)


def draw_hold_arc(frame, cx: int, cy: int, radius: int,
                  progress: float, color: tuple, just_completed: bool):
    """
    Circular progress arc.
    - Fills clockwise from the top as progress goes 0→1.
    - Flashes white briefly when just_completed is True.
    """
    bg_color = (255, 255, 255) if just_completed else (55, 55, 55)
    cv2.circle(frame, (cx, cy), radius + 4, bg_color, 2)

    if progress > 0:
        sweep = int(360 * progress)
        cv2.ellipse(frame, (cx, cy), (radius, radius),
                    -90, 0, sweep, color, thickness=7)

    label = "HOLD!" if just_completed else f"{int(progress * 100)}%"
    lw    = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.55, 2)[0][0]
    cv2.putText(frame, label, (cx - lw // 2, cy + 6),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55, color if not just_completed else (255,255,255), 2)


def draw_right_panel(frame, fb: FeedbackResult,
                     session: Session, config: dict,
                     pose_keys: list, current_idx: int,
                     ref_photos: dict):
    h, w   = frame.shape[:2]
    px     = w - 310
    tholds = config["feedback"]["score_thresholds"]

    draw_rounded_rect(frame, px - 10, 10, w - 5, h - 10, 12, (18, 18, 18), 0.68)

    # Pose name
    cv2.putText(frame, fb.pose_name,
                (px, 36), cv2.FONT_HERSHEY_DUPLEX, 0.60, (255, 255, 255), 1)

    # ── Coverage warning takes priority over score ────────────────
    if fb.insufficient_coverage:
        warn = "Step back — full body needed"
        cv2.putText(frame, warn,
                    (px, 63), cv2.FONT_HERSHEY_SIMPLEX, 0.42, (60, 60, 240), 1)
        cv2.putText(frame, f"({fb.n_visible} joints visible)",
                    (px, 80), cv2.FONT_HERSHEY_SIMPLEX, 0.37, (130, 130, 130), 1)
        # Still show reference photo so user knows what to aim for
        draw_pose_reference(frame, ref_photos.get(fb.pose_name), bx=px, by=93)
        hint = config["poses"].get(fb.pose_name, {}).get("tip", "")
        cv2.putText(frame, hint, (10, h - 15),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.35, (120, 120, 120), 1)
        return

    # ── Normal score display ──────────────────────────────────────
    sc = fb.score
    sc_col = ((50, 220, 80)  if sc >= tholds["green"]  else
              (30, 180, 255) if sc >= tholds["orange"] else
              (60, 60, 240))
    cv2.putText(frame, f"Score: {sc}%",
                (px, 63), cv2.FONT_HERSHEY_DUPLEX, 0.70, sc_col, 2)

    bw = 282
    cv2.rectangle(frame, (px, 73),  (px + bw, 85),               (50, 50, 50), -1)
    cv2.rectangle(frame, (px, 73),  (px + int(bw * sc / 100), 85), sc_col, -1)

    # Thumbnail / reference photo
    draw_pose_reference(frame, ref_photos.get(fb.pose_name), bx=px, by=93)

    # Rep counter (below thumbnail)
    reps = session.rep_count(fb.pose_name)
    cv2.putText(frame, f"Reps: {reps}",
                (px, 273), cv2.FONT_HERSHEY_SIMPLEX, 0.48, (180, 180, 180), 1)

    # Per-joint feedback
    y_off = 296
    for joint in fb.joints:
        if y_off > h - 65:
            break
        cv2.circle(frame, (px + 7, y_off - 4), 5, joint.color, -1)
        cv2.putText(frame, joint.name,
                    (px + 18, y_off),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.39, (215, 215, 215), 1)
        detail = f"{joint.measured:.0f}d  ref:{joint.target:.0f}d  ({joint.diff:+.0f})"
        cv2.putText(frame, detail,
                    (px + 18, y_off + 14),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.35, joint.color, 1)
        y_off += 37

    # Correction tip (bottom, worst joint)
    if fb.worst_joint and sc < tholds["green"]:
        j   = fb.worst_joint
        dir = "increase" if j.measured < j.target else "reduce"
        tip = f"Tip: {dir} {j.name} by {j.diff:.0f} deg"
        tip_right = min(w - 320, 660)
        draw_rounded_rect(frame, 10, h - 52, tip_right, h - 10, 8, (18, 18, 18), 0.75)
        cv2.putText(frame, tip, (18, h - 26),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.52, (30, 200, 255), 1)

    # Pose hint (bottom right)
    hint = config["poses"].get(fb.pose_name, {}).get("tip", "")
    cv2.putText(frame, hint, (10, h - 15),
                cv2.FONT_HERSHEY_SIMPLEX, 0.35, (120, 120, 120), 1)


def draw_top_bar(frame, pose_keys: list, current_idx: int, fps: float,
                 refs_loaded: bool):
    # Key legend
    for i, pn in enumerate(pose_keys):
        col = (50, 220, 80) if i == current_idx else (100, 100, 100)
        cv2.putText(frame, f"[{i+1}] {pn}", (10, 50 + i * 22),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.42, col, 1)

    # FPS
    cv2.putText(frame, f"FPS: {fps:.0f}", (10, 25),
                cv2.FONT_HERSHEY_SIMPLEX, 0.46, (120, 120, 120), 1)

    # Data source indicator
    src_label = "refs: dataset" if refs_loaded else "refs: MISSING — run build_references.py"
    src_color = (50, 200, 80) if refs_loaded else (60, 60, 240)
    w = frame.shape[1]
    cv2.putText(frame, src_label, (w - 310, frame.shape[0] - 5),
                cv2.FONT_HERSHEY_SIMPLEX, 0.33, src_color, 1)


# ─────────────────────────────────────────────────────────────────
#  SESSION SUMMARY HELPERS
# ─────────────────────────────────────────────────────────────────

def load_previous_session_stats(log_dir: str, current_path: str | None) -> dict | None:
    """
    Read the most recent CSV session file that is NOT the current session.
    Returns { pose_name: {"reps": int, "avg_score": float} } or None.
    """
    pattern = os.path.join(log_dir, "session_*.csv")
    files   = sorted(glob.glob(pattern))

    # Remove current session from candidates
    candidates = [f for f in files if f != current_path]
    if not candidates:
        return None

    prev_path = candidates[-1]
    stats: dict[str, dict] = {}

    try:
        with open(prev_path, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                pose = row.get("pose_name", "").strip()
                try:
                    score = float(row.get("score", 0))
                except ValueError:
                    continue
                if pose not in stats:
                    stats[pose] = {"reps": 0, "score_sum": 0.0}
                stats[pose]["reps"]      += 1
                stats[pose]["score_sum"] += score
    except Exception:
        return None

    return {
        pose: {
            "reps":      v["reps"],
            "avg_score": v["score_sum"] / v["reps"] if v["reps"] else 0,
        }
        for pose, v in stats.items()
    }


def show_session_summary(session: Session, refs: dict, config: dict):
    """
    Draw a full-screen summary panel and display it until the user
    presses any key or closes the window.

    Shows:
      - Rep count and average score per pose (this session)
      - Per-joint score breakdown with horizontal bar charts
      - Comparison with the previous session (if a CSV exists)
      - Next-session focus tip (worst joint)
    """
    from analyzer import ANGLE_INDICES

    reps = session._reps
    if not reps:
        return

    # ── Compute per-pose stats ───────────────────────────────────
    pose_stats: dict[str, dict] = {}
    for rep in reps:
        p = rep.pose_name
        if p not in pose_stats:
            pose_stats[p] = {"reps": 0, "score_sum": 0.0, "angle_sums": {}, "angle_counts": {}}
        pose_stats[p]["reps"]      += 1
        pose_stats[p]["score_sum"] += rep.score
        for angle_name, measured in rep.angles.items():
            pose_stats[p]["angle_sums"][angle_name]   = \
                pose_stats[p]["angle_sums"].get(angle_name, 0.0) + measured
            pose_stats[p]["angle_counts"][angle_name] = \
                pose_stats[p]["angle_counts"].get(angle_name, 0) + 1

    max_tol = float(config["feedback"].get("max_tolerance_deg", 25.0))

    def joint_score_from_avg(pose_name, angle_name, avg_measured):
        ref = refs.get(pose_name, {}).get(angle_name)
        if ref is None:
            return None
        tol  = min(float(ref["tolerance"]), max_tol)
        diff = abs(avg_measured - float(ref["target"]))
        return max(0.0, 100.0 - (diff / max(tol, 1e-6)) * 50.0)

    # ── Per-joint scores ─────────────────────────────────────────
    # Use the pose with the most reps as the primary display pose
    primary_pose = max(pose_stats, key=lambda p: pose_stats[p]["reps"])
    ps           = pose_stats[primary_pose]
    angle_keys   = config["poses"].get(primary_pose, {}).get("angle_keys", [])

    joint_scores: list[tuple[str, float]] = []
    for aname in angle_keys:
        count = ps["angle_counts"].get(aname, 0)
        if count == 0:
            continue
        avg_m = ps["angle_sums"][aname] / count
        sc    = joint_score_from_avg(primary_pose, aname, avg_m)
        if sc is not None:
            joint_scores.append((aname, sc))

    joint_scores.sort(key=lambda x: x[1])   # worst first

    # ── Previous session ─────────────────────────────────────────
    log_dir      = config["session"].get("log_dir", "sessions")
    prev_stats   = load_previous_session_stats(log_dir, session.summary()["session_file"])

    # ── Draw ─────────────────────────────────────────────────────
    W, H  = 900, 640
    frame = np.full((H, W, 3), 20, dtype=np.uint8)    # dark background

    TITLE_COL  = (255, 255, 255)
    DIM_COL    = (140, 140, 140)
    GREEN      = (50,  220, 80)
    ORANGE     = (30,  180, 255)
    RED        = (60,  60,  240)
    ACCENT     = (200, 160, 60)

    def txt(text, x, y, scale=0.55, color=TITLE_COL, thickness=1):
        cv2.putText(frame, text, (x, y),
                    cv2.FONT_HERSHEY_SIMPLEX, scale, color, thickness,
                    cv2.LINE_AA)

    def hline(y, x1=30, x2=W-30, col=(55, 55, 55)):
        cv2.line(frame, (x1, y), (x2, y), col, 1)

    def bar(x, y, pct, bar_w=200, bar_h=12, col=GREEN):
        cv2.rectangle(frame, (x, y), (x + bar_w, y + bar_h), (50, 50, 50), -1)
        fill = int(bar_w * max(0.0, min(1.0, pct / 100.0)))
        if fill > 0:
            cv2.rectangle(frame, (x, y), (x + fill, y + bar_h), col, -1)

    def score_col(s):
        return GREEN if s >= 75 else ORANGE if s >= 50 else RED

    # Title
    cv2.putText(frame, "Session Summary",
                (30, 45), cv2.FONT_HERSHEY_DUPLEX, 1.1, TITLE_COL, 2, cv2.LINE_AA)
    hline(60)

    y = 90

    # ── Per-pose block ───────────────────────────────────────────
    txt("This session", 30, y, 0.5, DIM_COL)
    y += 26

    for pose_name, ps_data in pose_stats.items():
        n_reps    = ps_data["reps"]
        avg_score = ps_data["score_sum"] / n_reps if n_reps else 0
        sc        = score_col(avg_score)

        txt(pose_name, 30, y, 0.58, TITLE_COL, 1)
        txt(f"{n_reps} rep{'s' if n_reps != 1 else ''}",
            280, y, 0.52, DIM_COL)
        txt(f"avg {avg_score:.0f}%", 380, y, 0.58, sc, 1)
        bar(490, y - 12, avg_score, bar_w=220, col=sc)

        # vs. last session
        if prev_stats and pose_name in prev_stats:
            prev_avg = prev_stats[pose_name]["avg_score"]
            delta    = avg_score - prev_avg
            arrow    = "↑" if delta >= 0 else "↓"
            dcol     = GREEN if delta >= 0 else RED
            txt(f"vs last: {prev_avg:.0f}%  {arrow}{abs(delta):.0f}%",
                730, y, 0.46, dcol)

        y += 32

    hline(y + 4)
    y += 24

    # ── Joint breakdown ──────────────────────────────────────────
    if joint_scores:
        txt(f"Joint breakdown — {primary_pose}", 30, y, 0.5, DIM_COL)
        y += 28

        bar_x     = 240
        worst_name = joint_scores[0][0]

        for aname, jscore in joint_scores:
            col  = score_col(jscore)
            flag = "  ← work on this" if aname == worst_name else ""
            txt(aname, 30, y, 0.46, TITLE_COL)
            txt(f"{jscore:.0f}%", bar_x - 50, y, 0.48, col)
            bar(bar_x, y - 11, jscore, bar_w=300, bar_h=11, col=col)
            if flag:
                txt(flag, bar_x + 310, y, 0.44, ORANGE)
            y += 30

        hline(y + 4)
        y += 24

    # ── Next-session tip ─────────────────────────────────────────
    if joint_scores:
        worst_name, worst_sc = joint_scores[0]
        ref = refs.get(primary_pose, {}).get(worst_name)
        if ref:
            txt("Next session focus:", 30, y, 0.52, DIM_COL)
            tip = (f"{worst_name}  (avg {worst_sc:.0f}%)  "
                   f"— target: {ref['target']:.0f}° ± {min(ref['tolerance'], max_tol):.0f}°")
            txt(tip, 210, y, 0.52, ACCENT, 1)
        y += 30

    # ── Progress across sessions ─────────────────────────────────
    if prev_stats:
        hline(y + 4)
        y += 24
        txt("Progress", 30, y, 0.5, DIM_COL)
        y += 26
        for pose_name in pose_stats:
            curr_avg = pose_stats[pose_name]["score_sum"] / pose_stats[pose_name]["reps"]
            if pose_name in prev_stats:
                prev_avg = prev_stats[pose_name]["avg_score"]
                delta    = curr_avg - prev_avg
                col      = GREEN if delta >= 0 else RED
                arrow    = "↑" if delta >= 0 else "↓"
                txt(f"{pose_name}: {prev_avg:.0f}%  →  {curr_avg:.0f}%  "
                    f"({arrow} {abs(delta):.0f}%)",
                    50, y, 0.52, col, 1)
                y += 28

    # Footer
    hline(H - 45)
    txt("Press any key to close",
        W // 2 - 110, H - 18, 0.50, DIM_COL)

    # ── Show ─────────────────────────────────────────────────────
    cv2.imshow("Session Summary", frame)
    cv2.waitKey(0)
    try:
        cv2.destroyWindow("Session Summary")
    except Exception:
        pass


# ─────────────────────────────────────────────────────────────────
#  MAIN LOOP
# ─────────────────────────────────────────────────────────────────
def main():
    config     = load_config("config.json")
    refs       = load_refs(config["refs_file"])
    refs_loaded = bool(refs)

    pose_keys     = list(config["poses"].keys())
    current_idx   = 0

    model_path = config["model_path"]
    if not os.path.exists(model_path):
        print(f"[ERROR] Model not found: {model_path}")
        print("        Download pose_landmarker.task from:")
        print("        https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker")
        sys.exit(1)

    landmarker = init_landmarker(model_path)
    session    = Session(config)
    smoother   = FeedbackSmoother(config)
    audio      = AudioFeedback(config)

    wc = config["webcam"]
    cap = cv2.VideoCapture(wc["index"])
    if not cap.isOpened():
        print(f"[ERROR] Could not open webcam (index {wc['index']}).")
        sys.exit(1)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH,  wc["width"])
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, wc["height"])

    print("\n═══════════════════════════════════════════")
    print("  Yoga Pose Feedback")
    print("═══════════════════════════════════════════")
    print(f"  Poses     : {pose_keys}")
    print(f"  References: {'loaded from dataset' if refs_loaded else '⚠ NOT FOUND'}")
    if refs_loaded:
        print(f"  Hold timer: {config['feedback']['hold_duration_s']}s "
              f"at score ≥ {config['feedback']['min_hold_score']}%")
    print("  Keys      : 1-3 select pose | Q quit")
    print("  Stand ~1.5 m from the webcam")
    print("  Loading reference photos…")
    ref_photos = load_reference_photos(config)
    print("═══════════════════════════════════════════\n")

    prev_time      = time.time()
    frame_ts       = 0
    just_completed = False       # flash state for one extra frame

    hold_duration  = config["feedback"]["hold_duration_s"]
    min_hold_score = config["feedback"]["min_hold_score"]

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame    = cv2.flip(frame, 1)
        rgb      = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)
        results  = landmarker.detect_for_video(mp_image, frame_ts)
        frame_ts += 1

        now       = time.time()
        fps       = 1.0 / (now - prev_time + 1e-6)
        prev_time = now

        pose_name = pose_keys[current_idx]
        h, w      = frame.shape[:2]

        # ── Extract landmarks ─────────────────────────────────────
        if results.pose_landmarks:
            lm_2d   = results.pose_landmarks[0]
            lm_world = (results.pose_world_landmarks[0]
                        if results.pose_world_landmarks else None)
        else:
            lm_2d    = None
            lm_world = None

        # ── Compute raw feedback ──────────────────────────────────
        if lm_2d and refs_loaded:
            raw_fb = compute_feedback(lm_2d, lm_world, pose_name, refs, config)
        else:
            raw_fb = FeedbackResult(pose_name=pose_name, score=0)

        # ── Smooth: stabilise angles + colours + throttle panel ───
        # stable_fb  → use for skeleton drawing (every frame, stable colours)
        # panel_ready → True when text panel should refresh (~every 0.5 s)
        stable_fb, panel_ready = smoother.update(raw_fb)

        # ── Session update (use stable score — avoids jittery hold timer) ─
        angle_vals = {j.name: j.measured for j in stable_fb.joints}
        if not stable_fb.insufficient_coverage:
            progress, completed = session.update(
                stable_fb.score, pose_name, angle_vals)
            if completed:
                audio.on_rep_completed()
                just_completed = True
        else:
            progress, completed = 0.0, False

        # ── Audio score alert (fires when score stays low for > 3 s) ──
        audio.update_score(stable_fb.score, stable_fb.insufficient_coverage)

        # ── Draw skeleton (every frame, uses stable colours) ──────
        if lm_2d:
            joint_colors = {
                ANGLE_INDICES[j.name][1]: j.color
                for j in stable_fb.joints
            }
            draw_skeleton(frame, lm_2d, joint_colors)
        else:
            cv2.putText(frame, "No person detected — move closer",
                        (w // 2 - 230, h // 2),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.9, (60, 60, 240), 2)

        # ── Right panel (throttled — only refreshes every 0.5 s) ──
        # When not ready, re-draw the last stable panel snapshot.
        panel_fb = stable_fb if panel_ready else smoother.last_panel_fb
        draw_right_panel(frame, panel_fb, session, config,
                         pose_keys, current_idx, ref_photos)

        # ── Hold arc (only when full body visible) ────────────────
        if not stable_fb.insufficient_coverage:
            panel_w = 315
            arc_cx  = (w - panel_w) // 2
            arc_cy  = h - 55
            arc_col = ((50, 220, 80)
                       if stable_fb.score >= config["feedback"]["score_thresholds"]["green"]
                       else (30, 180, 255))
            draw_hold_arc(frame, arc_cx, arc_cy, 38, progress, arc_col, just_completed)
        else:
            # Show "step back" warning on the video frame too
            warn_x = (w - 315) // 2 - 160
            draw_rounded_rect(frame, warn_x, h - 52, warn_x + 320, h - 10,
                               8, (18, 18, 18), 0.75)
            cv2.putText(frame, "Step back — full body needed",
                        (warn_x + 10, h - 26),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.52, (60, 60, 240), 1)

        just_completed = False

        # ── Top bar ───────────────────────────────────────────────
        draw_top_bar(frame, pose_keys, current_idx, fps, refs_loaded)

        cv2.imshow("Yoga Pose Feedback", frame)

        key = cv2.waitKey(1) & 0xFF
        if key in (ord("q"), 27):
            break
        elif key == ord("1") and len(pose_keys) >= 1:
            if current_idx != 0:
                smoother.reset()
                audio.reset()
            current_idx = 0
        elif key == ord("2") and len(pose_keys) >= 2:
            if current_idx != 1:
                smoother.reset()
                audio.reset()
            current_idx = 1
        elif key == ord("3") and len(pose_keys) >= 3:
            if current_idx != 2:
                smoother.reset()
                audio.reset()
            current_idx = 2

    # ── Shutdown ──────────────────────────────────────────────────
    try:
        landmarker.close()
    except Exception:
        pass
    cap.release()
    cv2.destroyAllWindows()

    # ── Post-session summary ──────────────────────────────────────
    summary = session.summary()
    print(f"\nSession ended.")
    print(f"  Total reps : {summary['total_reps']}")
    print(f"  By pose    : {summary['by_pose']}")
    if summary["session_file"]:
        print(f"  Log saved  : {summary['session_file']}")

    if summary["total_reps"] > 0:
        print("\nShowing session summary — press any key to close.")
        show_session_summary(session, refs, config)


if __name__ == "__main__":
    main()