"""
main.py — Yoga Pose Feedback System
=====================================
Entry point. Loads config.json and pose_references.json,
opens the webcam, and runs the real-time feedback loop.

Requirements
────────────
  pip install mediapipe opencv-python numpy

Files needed in the same directory
───────────────────────────────────
  config.json           ← parameters
  pose_references.json  ← generated by build_references.py
  pose_landmarker.task  ← MediaPipe model

Controls
────────
  1 / 2 / 3  — select pose
  Q / Esc    — quit
"""

import json
import math
import os
import sys
import time

import cv2
import mediapipe as mp
import numpy as np
from mediapipe.tasks import python as mp_python
from mediapipe.tasks.python import vision as mp_vision

from analyzer import ANGLE_INDICES, FeedbackResult, compute_feedback
from session  import Session


# ─────────────────────────────────────────────────────────────────
#  STARTUP — load config and references
# ─────────────────────────────────────────────────────────────────
def load_config(path="config.json") -> dict:
    if not os.path.exists(path):
        print(f"[ERROR] {path} not found.")
        sys.exit(1)
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_refs(path: str) -> dict:
    """Load pose_references.json. Returns {} if not found (triggers fallback in analyzer)."""
    if not os.path.exists(path):
        print(f"[WARN] {path} not found — no dataset references loaded.")
        print("       Run:  python build_references.py --yoga82 Yoga-82/")
        return {}
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    # Normalise: ensure every value has "target" and "tolerance" floats
    refs = {}
    for pose, angles in data.items():
        refs[pose] = {}
        for angle, v in angles.items():
            refs[pose][angle] = {
                "target":    float(v["target"]),
                "tolerance": float(v["tolerance"]),
            }
    return refs


# ─────────────────────────────────────────────────────────────────
#  MEDIAPIPE INIT
# ─────────────────────────────────────────────────────────────────
def init_landmarker(model_path: str):
    opts = mp_vision.PoseLandmarkerOptions(
        base_options=mp_python.BaseOptions(model_asset_path=model_path),
        running_mode=mp_vision.RunningMode.VIDEO,
        num_poses=1,
    )
    return mp_vision.PoseLandmarker.create_from_options(opts)


# ─────────────────────────────────────────────────────────────────
#  POSE THUMBNAIL REFERENCE POSITIONS
#  Normalised (0–100) landmark positions for each pose.
#  These are visual constants — they represent ideal body geometry
#  and are appropriate in code, not config.
# ─────────────────────────────────────────────────────────────────
POSE_THUMBNAILS = {
    "Warrior I": {
        0:  (50,  6),
        11: (42, 26),  12: (58, 26),
        13: (36, 10),  14: (64, 10),
        15: (32,  0),  16: (68,  0),
        23: (44, 57),  24: (56, 54),
        25: (30, 82),  26: (73, 72),
        27: (24, 108), 28: (83, 97),
    },
    "Tree Pose": {
        0:  (50,  6),
        11: (38, 26),  12: (62, 26),
        13: (44, 42),  14: (56, 42),
        15: (50, 52),  16: (50, 52),
        23: (46, 63),  24: (54, 63),
        25: (34, 80),  26: (54, 88),
        27: (38, 88),  28: (54, 113),
    },
    "Triangle": {
        0:  (44, 10),
        11: (28, 30),  12: (66, 42),
        13: (16, 24),  14: (76, 60),
        15: ( 8, 18),  16: (82, 73),
        23: (36, 63),  24: (60, 63),
        25: (26, 88),  26: (68, 88),
        27: (16, 113), 28: (78, 113),
    },
}

STICK_CONNECTIONS = [
    ( 0, 11), ( 0, 12), (11, 12),
    (11, 13), (13, 15), (12, 14), (14, 16),
    (11, 23), (12, 24), (23, 24),
    (23, 25), (25, 27), (24, 26), (26, 28),
]

SKELETON_CONNECTIONS = [
    (11, 13), (13, 15), (12, 14), (14, 16),
    (15, 17), (15, 19), (16, 18), (16, 20),
    (23, 25), (25, 27), (24, 26), (26, 28),
    (11, 12), (23, 24), (11, 23), (12, 24),
    ( 0, 11), ( 0, 12),
]


# ─────────────────────────────────────────────────────────────────
#  DRAWING HELPERS
# ─────────────────────────────────────────────────────────────────
def draw_rounded_rect(img, x1, y1, x2, y2, r, color, alpha=0.60):
    ov = img.copy()
    cv2.rectangle(ov, (x1 + r, y1), (x2 - r, y2), color, -1)
    cv2.rectangle(ov, (x1, y1 + r), (x2, y2 - r), color, -1)
    for cx, cy in [(x1+r, y1+r), (x2-r, y1+r), (x1+r, y2-r), (x2-r, y2-r)]:
        cv2.circle(ov, (cx, cy), r, color, -1)
    cv2.addWeighted(ov, alpha, img, 1 - alpha, 0, img)


def draw_skeleton(frame, lm_2d, joint_colors: dict):
    h, w = frame.shape[:2]
    for si, ei in SKELETON_CONNECTIONS:
        if si >= len(lm_2d) or ei >= len(lm_2d):
            continue
        ls, le = lm_2d[si], lm_2d[ei]
        if getattr(ls, "visibility", 1) < 0.4 or getattr(le, "visibility", 1) < 0.4:
            continue
        xs, ys = int(ls.x * w), int(ls.y * h)
        xe, ye = int(le.x * w), int(le.y * h)
        cs  = joint_colors.get(si, (200, 200, 200))
        ce  = joint_colors.get(ei, (200, 200, 200))
        seg = tuple(int(v) for v in ((np.array(cs) + np.array(ce)) // 2))
        cv2.line(frame, (xs, ys), (xe, ye), seg, 2)

    for idx, lm in enumerate(lm_2d):
        if getattr(lm, "visibility", 1) < 0.4:
            continue
        x, y = int(lm.x * w), int(lm.y * h)
        col  = joint_colors.get(idx, (180, 180, 180))
        cv2.circle(frame, (x, y), 5, col, -1)
        cv2.circle(frame, (x, y), 5, (255, 255, 255), 1)


def draw_pose_thumbnail(frame, pose_name: str, bx: int, by: int,
                        bw: int = 130, bh: int = 165):
    pts = POSE_THUMBNAILS.get(pose_name)
    if pts is None:
        return
    draw_rounded_rect(frame, bx, by, bx + bw, by + bh, 8, (28, 28, 28), 0.80)
    cv2.putText(frame, "Target", (bx + 8, by + 14),
                cv2.FONT_HERSHEY_SIMPLEX, 0.34, (150, 150, 150), 1)

    mg = 10
    dw = bw - mg * 2
    dh = bh - mg - 20

    def to_px(nx, ny):
        return (bx + mg + int(nx / 100 * dw), by + 20 + int(ny / 100 * dh))

    for ai, bi in STICK_CONNECTIONS:
        if ai in pts and bi in pts:
            cv2.line(frame, to_px(*pts[ai]), to_px(*pts[bi]), (110, 140, 220), 1)
    for idx, (nx, ny) in pts.items():
        cv2.circle(frame, to_px(nx, ny), 4 if idx == 0 else 3, (195, 205, 255), -1)


def draw_hold_arc(frame, cx: int, cy: int, radius: int,
                  progress: float, color: tuple, just_completed: bool):
    """
    Circular progress arc.
    - Fills clockwise from the top as progress goes 0→1.
    - Flashes white briefly when just_completed is True.
    """
    bg_color = (255, 255, 255) if just_completed else (55, 55, 55)
    cv2.circle(frame, (cx, cy), radius + 4, bg_color, 2)

    if progress > 0:
        sweep = int(360 * progress)
        cv2.ellipse(frame, (cx, cy), (radius, radius),
                    -90, 0, sweep, color, thickness=7)

    label = "HOLD!" if just_completed else f"{int(progress * 100)}%"
    lw    = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.55, 2)[0][0]
    cv2.putText(frame, label, (cx - lw // 2, cy + 6),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55, color if not just_completed else (255,255,255), 2)


def draw_right_panel(frame, fb: FeedbackResult,
                     session: Session, config: dict,
                     pose_keys: list, current_idx: int):
    h, w   = frame.shape[:2]
    px     = w - 310
    tholds = config["feedback"]["score_thresholds"]

    draw_rounded_rect(frame, px - 10, 10, w - 5, h - 10, 12, (18, 18, 18), 0.68)

    # Pose name
    cv2.putText(frame, fb.pose_name,
                (px, 36), cv2.FONT_HERSHEY_DUPLEX, 0.60, (255, 255, 255), 1)

    # Score
    sc = fb.score
    sc_col = ((50, 220, 80)  if sc >= tholds["green"]  else
              (30, 180, 255) if sc >= tholds["orange"] else
              (60, 60, 240))
    cv2.putText(frame, f"Score: {sc}%",
                (px, 63), cv2.FONT_HERSHEY_DUPLEX, 0.70, sc_col, 2)

    bw = 282
    cv2.rectangle(frame, (px, 73),  (px + bw, 85),               (50, 50, 50), -1)
    cv2.rectangle(frame, (px, 73),  (px + int(bw * sc / 100), 85), sc_col, -1)

    # Thumbnail
    draw_pose_thumbnail(frame, fb.pose_name, bx=px, by=93)

    # Rep counter (below thumbnail)
    reps = session.rep_count(fb.pose_name)
    cv2.putText(frame, f"Reps: {reps}",
                (px, 273), cv2.FONT_HERSHEY_SIMPLEX, 0.48, (180, 180, 180), 1)

    # Per-joint feedback
    y_off = 296
    for joint in fb.joints:
        if y_off > h - 65:
            break
        cv2.circle(frame, (px + 7, y_off - 4), 5, joint.color, -1)
        cv2.putText(frame, joint.name,
                    (px + 18, y_off),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.39, (215, 215, 215), 1)
        detail = f"{joint.measured:.0f}d  ref:{joint.target:.0f}d  ({joint.diff:+.0f})"
        cv2.putText(frame, detail,
                    (px + 18, y_off + 14),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.35, joint.color, 1)
        y_off += 37

    # Correction tip (bottom, worst joint)
    if fb.worst_joint and sc < tholds["green"]:
        j   = fb.worst_joint
        dir = "increase" if j.measured < j.target else "reduce"
        tip = f"Tip: {dir} {j.name} by {j.diff:.0f} deg"
        tip_right = min(w - 320, 660)
        draw_rounded_rect(frame, 10, h - 52, tip_right, h - 10, 8, (18, 18, 18), 0.75)
        cv2.putText(frame, tip, (18, h - 26),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.52, (30, 200, 255), 1)

    # Pose hint (bottom right)
    hint = config["poses"].get(fb.pose_name, {}).get("tip", "")
    cv2.putText(frame, hint, (10, h - 15),
                cv2.FONT_HERSHEY_SIMPLEX, 0.35, (120, 120, 120), 1)


def draw_top_bar(frame, pose_keys: list, current_idx: int, fps: float,
                 refs_loaded: bool):
    # Key legend
    for i, pn in enumerate(pose_keys):
        col = (50, 220, 80) if i == current_idx else (100, 100, 100)
        cv2.putText(frame, f"[{i+1}] {pn}", (10, 50 + i * 22),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.42, col, 1)

    # FPS
    cv2.putText(frame, f"FPS: {fps:.0f}", (10, 25),
                cv2.FONT_HERSHEY_SIMPLEX, 0.46, (120, 120, 120), 1)

    # Data source indicator
    src_label = "refs: dataset" if refs_loaded else "refs: MISSING — run build_references.py"
    src_color = (50, 200, 80) if refs_loaded else (60, 60, 240)
    w = frame.shape[1]
    cv2.putText(frame, src_label, (w - 310, frame.shape[0] - 5),
                cv2.FONT_HERSHEY_SIMPLEX, 0.33, src_color, 1)


# ─────────────────────────────────────────────────────────────────
#  MAIN LOOP
# ─────────────────────────────────────────────────────────────────
def main():
    config     = load_config("config.json")
    refs       = load_refs(config["refs_file"])
    refs_loaded = bool(refs)

    pose_keys     = list(config["poses"].keys())
    current_idx   = 0

    model_path = config["model_path"]
    if not os.path.exists(model_path):
        print(f"[ERROR] Model not found: {model_path}")
        print("        Download pose_landmarker.task from:")
        print("        https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker")
        sys.exit(1)

    landmarker = init_landmarker(model_path)
    session    = Session(config)

    wc = config["webcam"]
    cap = cv2.VideoCapture(wc["index"])
    if not cap.isOpened():
        print(f"[ERROR] Could not open webcam (index {wc['index']}).")
        sys.exit(1)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH,  wc["width"])
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, wc["height"])

    print("\n═══════════════════════════════════════════")
    print("  Yoga Pose Feedback")
    print("═══════════════════════════════════════════")
    print(f"  Poses     : {pose_keys}")
    print(f"  References: {'loaded from dataset' if refs_loaded else '⚠ NOT FOUND'}")
    if refs_loaded:
        print(f"  Hold timer: {config['feedback']['hold_duration_s']}s "
              f"at score ≥ {config['feedback']['min_hold_score']}%")
    print("  Keys      : 1-3 select pose | Q quit")
    print("  Stand ~1.5 m from the webcam\n")

    prev_time      = time.time()
    frame_ts       = 0
    just_completed = False       # flash state for one extra frame

    hold_duration  = config["feedback"]["hold_duration_s"]
    min_hold_score = config["feedback"]["min_hold_score"]

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame    = cv2.flip(frame, 1)
        rgb      = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)
        results  = landmarker.detect_for_video(mp_image, frame_ts)
        frame_ts += 1

        now       = time.time()
        fps       = 1.0 / (now - prev_time + 1e-6)
        prev_time = now

        pose_name = pose_keys[current_idx]
        h, w      = frame.shape[:2]

        # ── Extract landmarks ─────────────────────────────────────
        if results.pose_landmarks:
            lm_2d   = results.pose_landmarks[0]
            lm_world = (results.pose_world_landmarks[0]
                        if results.pose_world_landmarks else None)
        else:
            lm_2d    = None
            lm_world = None

        # ── Compute feedback ──────────────────────────────────────
        if lm_2d and refs_loaded:
            fb = compute_feedback(lm_2d, lm_world, pose_name, refs, config)
        else:
            fb = FeedbackResult(pose_name=pose_name, score=0)

        # ── Session update ────────────────────────────────────────
        angle_vals = {j.name: j.measured for j in fb.joints}
        progress, completed = session.update(fb.score, pose_name, angle_vals)
        if completed:
            just_completed = True

        # ── Draw skeleton ─────────────────────────────────────────
        if lm_2d:
            joint_colors = {
                ANGLE_INDICES[j.name][1]: j.color
                for j in fb.joints
            }
            draw_skeleton(frame, lm_2d, joint_colors)
        else:
            cv2.putText(frame, "No person detected — move closer",
                        (w // 2 - 230, h // 2),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.9, (60, 60, 240), 2)

        # ── Right panel ───────────────────────────────────────────
        draw_right_panel(frame, fb, session, config, pose_keys, current_idx)

        # ── Hold arc (bottom-centre of camera area) ───────────────
        panel_w = 315
        arc_cx  = (w - panel_w) // 2
        arc_cy  = h - 55
        arc_col = ((50, 220, 80) if fb.score >= config["feedback"]["score_thresholds"]["green"]
                   else (30, 180, 255))
        draw_hold_arc(frame, arc_cx, arc_cy, 38, progress, arc_col, just_completed)
        just_completed = False   # show flash for only one frame

        # ── Top bar ───────────────────────────────────────────────
        draw_top_bar(frame, pose_keys, current_idx, fps, refs_loaded)

        cv2.imshow("Yoga Pose Feedback", frame)

        key = cv2.waitKey(1) & 0xFF
        if key in (ord("q"), 27):
            break
        elif key == ord("1") and len(pose_keys) >= 1:
            current_idx = 0
        elif key == ord("2") and len(pose_keys) >= 2:
            current_idx = 1
        elif key == ord("3") and len(pose_keys) >= 3:
            current_idx = 2

    # ── Shutdown ──────────────────────────────────────────────────
    try:
        landmarker.close()
    except Exception:
        pass
    cap.release()
    cv2.destroyAllWindows()

    summary = session.summary()
    print(f"\nSession ended.")
    print(f"  Total reps : {summary['total_reps']}")
    print(f"  By pose    : {summary['by_pose']}")
    if summary["session_file"]:
        print(f"  Log saved  : {summary['session_file']}")


if __name__ == "__main__":
    main()